[![Coach Pegasus PNG- colab.png]()](https://yigitbravecesur.com/)

### 🔗 Links


[![linkedin](https://img.shields.io/badge/LinkedIn-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/yigitbcesur)

[![Youtube](https://img.shields.io/badge/youtube_channel-1DA1F2?style=for-the-badge&logo=youtube&logoColor=white&color=FF0000)](https://www.youtube.com/channel/UCYLMENl4ruLkZbCqLmIKW7A)

[![Twitter URL](https://img.shields.io/twitter/url/https/twitter.com/YigitBraveCesur.svg?style=social&label=Follow%20%40YigitBraveCesur)](https://twitter.com/YigitBraveCesur)

**Libraries**

In [ ]:
import pandas as pd
import numpy as np

# **CREATING OWN DATASET  DATASET**

### **"STOCKS"  dataset :**
Let's create a datetime index starting at 2022-01-03 ( Daily ) with 100 values

In [ ]:
index = pd.date_range(start='2022-01-03', periods=100, freq='D')

# Generate random values between 1 and 100
rand_values = np.random.randint(1, 101, size=100)

# Create a pandas DataFrame with the datetime index and random values
stocks = pd.DataFrame({'datetime': index, 'stock1': rand_values , 'price2': rand_values})

# Print the pandas DataFrame
print(stocks)

# saving dataset
stocks.to_csv('stocks.csv')

     datetime  stock1  price2
0  2022-01-03      56      56
1  2022-01-04      53      53
2  2022-01-05      91      91
3  2022-01-06      76      76
4  2022-01-07      49      49
..        ...     ...     ...
95 2022-04-08      22      22
96 2022-04-09      31      31
97 2022-04-10      68      68
98 2022-04-11      23      23
99 2022-04-12      14      14

[100 rows x 3 columns]

### **Create 100 rows + 5 columns ( numerical + categorical variables )dataset**

In [ ]:
import pandas as pd
import random

# Define the US States and car_purchased categories
us_states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

graduate_categories = ["High School", "Middle School", "Bachelor's", "Master's", "Doctorate"]
car_purchased_categories = ["Yes", "No"]

# Create a list to store the data
data = []

# Generate random data for the dataset
for _ in range(100):
    state = random.choice(us_states)
    age = random.randint(18, 65)
    salary = round(random.uniform(30000, 100000), -3)  # Round to the nearest thousand
    graduate = random.choice(graduate_categories)
    car_purchased = random.choice(car_purchased_categories)
    data.append([state, age, salary, graduate, car_purchased])

# Create a DataFrame
purchased = pd.DataFrame(data, columns=["US States", "Ages", "Salary", "Graduate", "Car Purchased"])


# Print the first few rows of the dataset
print(purchased.head())

# saving dataset
purchased.to_csv('purchased.csv')

   US States  Ages   Salary       Graduate Car Purchased
0    Montana    33  66000.0      Doctorate           Yes
1  Tennessee    27  34000.0    High School            No
2     Alaska    22  31000.0      Doctorate            No
3    Wyoming    44  54000.0  Middle School           Yes
4       Iowa    29  36000.0     Bachelor's            No

### **"HOUSES"  dataset :**

we generate a dataset with 300 houses. We introduce outliers for the "price" column and missing values for the "square_feet" and "year_built" columns. You can further customize the data generation process, outlier rates, and missing value rates to meet your specific needs

In [ ]:
# Define ordinal categories for crime_zone
crime_zone_categories = ["Low", "Middle", "High"]

# Define features
data = []

for _ in range(300):
    location = f"Location_{random.randint(1, 10)}"
    bedrooms = random.randint(1, 6)
    bathrooms = random.uniform(1, 4)
    crime_zone = random.choice(crime_zone_categories)
    swimming_pool = random.choice(["Yes", "No"])
    square_feet = random.randint(1000, 4000)
    year_built = random.randint(1960, 2023)
    has_basement = random.choice(["Yes", "No"])
    has_garage = random.choice(["Yes", "No"])
    price = random.randint(100000, 1000000)

    # Introduce missing values randomly
    if random.random() < 0.02:
        square_feet = np.nan
    if random.random() < 0.04:
        year_built = np.nan
    if random.random() < 0.05:
        bedrooms = np.nan
    if random.random() < 0.02:
        bathrooms = np.nan
    if random.random() < 0.05:
        has_basement = np.nan
    if random.random() < 0.05:
        has_garage = np.nan
    if random.random() < 0.02:
        swimming_pool = np.nan
    if random.random() < 0.03:
        crime_zone = np.nan


    data.append([location, bedrooms, bathrooms, crime_zone, swimming_pool, square_feet, year_built, has_basement, has_garage, price])

# Create a DataFrame
houses = pd.DataFrame(data, columns=["Location", "Bedrooms", "Bathrooms", "Crime Zone", "Swimming Pool", "Square Feet", "Year Built", "Has Basement", "Has Garage", "Price"])

# Print the first few rows of the dataset
print(houses.head())

# saving dataset
houses.to_csv('houses.csv')

      Location  Bedrooms  Bathrooms Crime Zone Swimming Pool  Square Feet  \
0   Location_3       2.0   1.348838     Middle            No       1121.0
1   Location_2       6.0   2.527034        Low           Yes       3884.0
2  Location_10       5.0   3.610300       High            No       2807.0
3   Location_9       6.0   2.434892       High           Yes       2925.0
4   Location_2       1.0   1.543335       High            No       1152.0

   Year Built Has Basement Has Garage   Price
0      1970.0           No         No  255158
1      1964.0          Yes         No  956782
2      2008.0          Yes         No  426694
3      2012.0           No        Yes  884693
4      1971.0          Yes         No  189457

In [ ]:
houses.isnull().sum()

Location          0
Bedrooms         14
Bathrooms         4
Crime Zone       14
Swimming Pool     6
Square Feet       9
Year Built        6
Has Basement     12
Has Garage       11
Price             0
dtype: int64

### **"SALES" dataset :**
Creating a synthetic **Sales** dataset with 1000 rows and 9 columns including missing values, outliers, and a mix of numeric and ordinal-nominal values

In [ ]:
# Set a random seed for reproducibility
np.random.seed(0)

# Generate data for the sales dataset
n = 1000

data = {
    'OrderID': range(1, n + 1),
    'Product': np.random.choice(['Product A', 'Product B', 'Product C', 'Product D'], n),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Home Appliances', 'Toys'], n),
    'Quantity': np.random.randint(1, 100, n),
    'Price': np.random.uniform(10, 500, n),
    'Discount': np.random.choice([0, 0.05, 0.1, 0.15], n),
    'Customer Rating': np.random.uniform(1, 5, n),
    'Delivery Time (days)': np.random.randint(1, 10, n),
    'Sales Rep': np.random.choice(['John', 'Sarah', 'Mike', 'Emily'], n),
}

# Introduce missing values
for column in data:
    missing_indices = np.random.choice(range(n), size=n//10, replace=False)
    data[column] = np.where(np.isin(range(n), missing_indices), np.nan, data[column])

# Introduce outliers
data['Price'][data['Price'] > 450] = data['Price'][data['Price'] > 450] * 2
data['Quantity'][data['Quantity'] > 80] = data['Quantity'][data['Quantity'] > 80] * 2

# Create the DataFrame
sales = pd.DataFrame(data)

# Display the first few rows of the dataset
print(sales.head())

# Save the dataset to a CSV file
sales.to_csv('sales.csv', index=False)

   OrderID    Product         Category  Quantity       Price  Discount  \
0      1.0  Product A              nan     164.0  208.836532      0.00
1      2.0  Product D  Home Appliances      30.0  982.760091      0.00
2      3.0  Product B             Toys      71.0  331.999142      0.05
3      4.0        nan      Electronics      29.0  381.160713      0.10
4      5.0  Product D      Electronics      75.0   20.617776      0.00

   Customer Rating  Delivery Time (days) Sales Rep
0         4.383246                   7.0     Emily
1         2.384325                   8.0     Sarah
2              NaN                   NaN     Emily
3         1.945488                   1.0      Mike
4         4.601915                   NaN      John

# **IMPORTING DATASET**

In [ ]:
stocks= pd.read_csv('sales.csv')
stocks

,OrderID,Product,Category,Quantity,Price,Discount,Customer Rating,Delivery Time (days),Sales Rep
0,1.0,Product A,NaN,164.0,208.836532,0.00,4.383246,7.0,Emily
1,2.0,Product D,Home Appliances,30.0,982.760091,0.00,2.384325,8.0,Sarah
2,3.0,Product B,Toys,71.0,331.999142,0.05,NaN,NaN,Emily
3,4.0,NaN,Electronics,29.0,381.160713,0.10,1.945488,1.0,Mike
4,5.0,Product D,Electronics,75.0,20.617776,0.00,4.601915,NaN,John
...,...,...,...,...,...,...,...,...,...
995,996.0,Product A,Clothing,NaN,50.953483,NaN,2.723933,6.0,Mike
996,997.0,Product A,NaN,45.0,288.433320,0.05,2.206266,NaN,John
997,998.0,Product C,Clothing,70.0,67.165956,0.05,3.323341,3.0,Mike
998,999.0,Product B,Clothing,17.0,31.013396,0.15,2.812793,3.0,John
999,1000.0,Product A,Clothing,17.0,197.994374,0.15,2.849074,9.0,NaN